-- CreateEnum
CREATE TYPE "PayPeriodType" AS ENUM ('WEEKLY', 'FORTNIGHTLY', 'MONTHLY');

-- AlterTable
ALTER TABLE "User" ADD COLUMN "payPeriodType" "PayPeriodType" NOT NULL DEFAULT 'WEEKLY';
ALTER TABLE "User" ADD COLUMN "paydayOfWeek" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "User" ADD COLUMN "paydayOfMonth" INTEGER NOT NULL DEFAULT 28;
ALTER TABLE "User" ADD COLUMN "payPeriodAnchor" DATE;
